main: co.xenocraft.QuickWarp
name: QuickWarp
version: 0.1
author: Blink9085
description: QuickWarp Plugin for Xenocraft Server
api-version: 1.18

commands:
  god:
    description: Become God?
    usage: /<command>
    permission: quickwarp.god
    permission-message: You really think you can become a God.
  createWarp:
    description: Creates a new Warp point under feet. Creates a new command block below the surface. Use range for discovery range. Use secret for different text style.
    usage: /<command> <name> <range> <secret> (Use underscore for spaces.)
    permission: quickwarp.createWarp
    permission-message: You don't have permission to do that.
  createWorldName:
    description: Creates the World for the warp points. This needs to be done before any warp points can be placed.
    usage: /<command> <name>
    permission: quickwarp.createWorldName
    permission-message: You don't have permission to do that.
  editWorld:
    description: Edit the name, desc, order, and block of the current world.
    usage: /<command> <name/edit/delete/desc/order/block>
    permission: quickwarp.editWorld
    permission-message: You don't have permission to do that.
  view:
    description: View all worlds or warp in your current worlds.
    permission: quickwarp.view
    permission-message: You don't have permission to do that.
  discoverWarp:
    description: Discover warp points for a player
    usage: /<command>
    permission: command
    permission-message: This is not a command you can use.
  warp:
    description: Opens warp menu.
    usage: /<command>
    permission: quickwarp.warp

permissions:
  quickwarp.warpEditor:
    description: Gives access so you can create, edit, see, or remove warp points.
    default: op
    children:
      quickwarp.createWarp: true
      quickwarp.createWorldName: true
      quickwarp.editWorld: true
      quickwarp.view: true
  quickwarp.createWarp:
    description: Allows one to create warp point.
    default: op
  quickwarp.createWorldName:
    description: Allows one to create worlds to warp to.
    default: op
  quickwarp.editWorld:
    description: Allows you to edit the worlds.
    default: op
  quickwarp.view:
    description: Allows you to see all create worlds or warp points.
    default: op
  quickwarp.warp:
    description: Allows one to teleport through the dimensions.
    default: true
  quickwarp.god:
    description: Allows one to become God.
    default: op