main: co.xenocraft.QuickWarp
name: QuickWarp
version: 1.0
author: Blink9085
description: QuickWarp Plugin
api-version: 1.18

commands:
  god:
    description: Become God?
    usage: /<command>
    permission: quickwarp.god
    permission-message: You really think you can become a God.
  createWarp:
    description: Creates a new warp point under feet. Creates a new command block below the surface. Use underscores _ for spaces. Use range for discovery range. Use secret for different text style.
    usage: /<command> <name> <range> <secret> (Use underscore for spaces.)
    permission: quickwarp.createWarp
    permission-message: You don't have permission to do that.
  createWorldName:
    description: Creates the World for the warp points. This needs to be done before any warp points can be created.
    usage: /<command> <name>
    permission: quickwarp.createWorldName
    permission-message: You don't have permission to do that.
  editWorld:
    description: Edit the name, desc, order, and block of the current world. Or remove it.
    usage: /<command> <name/edit/delete/desc/order/block> <options>
    permission: quickwarp.editWorld
    permission-message: You don't have permission to do that.
  editWarp:
    description: Edit the name, order and block of a warp point. Or remove it. Must be in same world as warp point you want to edit.
    usage: /<command> <warp point> <name/order/block/delete> <options>
    permission: quickwarp.editWarp
    permission-message: You don't have permission to do that.
  view:
    description: View all worlds or warp in your current worlds.
    usage: /<command>
    permission: quickwarp.view
    permission-message: You don't have permission to do that.
  discoverWarp:
    description: For command blocks only.
    usage: /<command>
    permission: quickwarp.discovery
    permission-message: This is not a command you can use.
  warp:
    description: Opens warp menu. Displays all discovered worlds and warp points.
    usage: /<command>
    permission: quickwarp.warp

permissions:
  quickwarp.warpEditor:
    description: Gives access so you can create, edit, see, or remove warp points. Includes all the permissions needed to create and edit all the warp points and worlds.
    default: op
    children:
      quickwarp.createWarp: true
      quickwarp.createWorldName: true
      quickwarp.editWorld: true
      quickwarp.editWarp: true
      quickwarp.view: true
  quickwarp.createWarp:
    description: Allows one to create warp point.
    default: op
  quickwarp.createWorldName:
    description: Allows one to create a world that stores warp points.
    default: op
  quickwarp.editWorld:
    description: Allows one to edit a world.
    default: op
  quickwarp.editWarp:
    description: Allows one to edit a warp point.
    default: op
  quickwarp.view:
    description: Allows one to see all created worlds or warp points.
    default: op
  quickwarp.warp:
    description: Allows one to teleport through the dimensions. Should be auto given to players.
    default: true
  quickwarp.discovery:
    description: For command block only.
    default: false
  quickwarp.god:
    description: Allows one to become God. Should not be given to players.
    default: op